[world]
height = 1000
width = 1000
scale = 10.0
fps = 20

#[[obstacles]]
#color = "white"
#shape = "box"
#width = 1.0
#height = 1.0
#x = 0.0
#y = 0.0
#theta = 0.0

[[agents]]
name = "tom"
type = "patrol"
waypoint = { x = 20.0, y = 20.0 }
speed = 20.0
shape = "circle"
radius = 2.0
x = 0.0
y = 0.0
theta = 0.0

[[agents]]
name = "jerry"
type = "vfh"
grid = { width = 1000, height = 1000 }
sensor = { count = 36, range = 30.0 }
shape = "box"
width = 4.0
height = 4.0
x = -10.00
y = 0.0
theta = 0.0
