[world]
height = 1000
width = 1000
scale = 10.0
fps = 100

[[obstacles]]
color = "white"
shape = "box"
width = 10.0
height = 20.0
x = 15.0
y = 0.0
theta = 0.0

[[obstacles]]
color = "white"
shape = "box"
width = 10.0
height = 20.0
x = -15.0
y = 0.0
theta = 0.0

[[obstacles]]
color = "white"
shape = "box"
width = 50.0
height = 5.0
x = 0.0
y = -30.0
theta = 0.0

[[markers]]
color = "green"
shape = "circle"
radius = 0.5
x = 25.0
y = 10.0
theta = 0.0

[[agents]]
name = "jerry"
type = "vfh"
loging = true
grid = { width = 1000, height = 1000 }
sensor = { count = 24, range = 25.0 }
goal = { x = 25.0, y = 10.0 }
valley_threshold = 250000
speed = 5.0
shape = "box"
width = 2.0
height = 2.0
x = -30.0
y = -15.0
theta = 0.0
