[world]
height = 1000
width = 1000
scale = 10.0
fps = 100

[[agents]]
name = "tom"
type = "vfh"
grid = { width = 1000, height = 1000 }
sensor = { count = 36, range = 50.0 }
goal = { x = 10.0, y = 0.0 }
valley_threshold = 10000
shape = "circle"
radius = 2.0
x = -20.0
y = 0.0
theta = 0.0

[[agents]]
name = "jerry"
type = "vfh"
grid = { width = 1000, height = 1000 }
sensor = { count = 36, range = 50.0 }
goal = { x = -10.0, y = 0.0 }
valley_threshold = 10000
shape = "box"
width = 4.0
height = 4.0
x = 10.0
y = 0.0
theta = 0.0
