[world]
height = 1000
width = 1000
scale = 10.0
fps = 100

#[[obstacles]]
#color = "white"
#shape = "box"
#width = 1.0
#height = 1.0
#x = 0.0
#y = 0.0
#theta = 0.0

[[agents]]
name = "jerry"
type = "vfh"
grid = { width = 1000, height = 1000 }
sensor = { count = 36, range = 50.0 }
goal = { x = 30.0, y = 0.0 }
valley_threshold = 10000
shape = "box"
width = 4.0
height = 4.0
x = 0.0
y = 1.0
theta = 0.0
