[world]
height = 1000
width = 1000
scale = 10.0
fps = 100

[[markers]]
shape = "circle"
radius = 0.5
color = "green"
x = 0.0
y = 10.0
theta = 0.0

[[agents]]
name = "tom"
type = "patrol"
color = "red"
waypoint = { x = 10.0, y = 0.0 }
speed = 2.0
shape = "circle"
radius = 3.0
x = -5.0
y = 0.0
theta = 0.0

[[agents]]
name = "jerry"
type = "vfh"
grid = { width = 1000, height = 1000 }
sensor = { count = 24, range = 25.0 }
goal = { x = 0.0, y = 10.0 }
valley_threshold = 250000
speed = 5.0
shape = "box"
width = 2.0
height = 2.0
x = 0.0
y = -12.0
theta = 0.0
